# NOTE: This file is auto generated by OpenAPI Generator
# https://openapi-generator.tech
# Do not edit this file manually.

defmodule DocuSign.Model.AccountPasswordLockoutDurationMinutes do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :maximumMinutes,
    :minimumMinutes
  ]

  @type t :: %__MODULE__{
          :maximumMinutes => String.t() | nil,
          :minimumMinutes => String.t() | nil
        }

  def decode(value) do
    value
  end
end
