# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DocuSign.Model.AccountPasswordLockoutDurationMinutes do
  @moduledoc false

  @derive [Poison.Encoder]
  defstruct [
    :maximumMinutes,
    :minimumMinutes
  ]

  @type t :: %__MODULE__{
          :maximumMinutes => String.t(),
          :minimumMinutes => String.t()
        }
end

defimpl Poison.Decoder, for: DocuSign.Model.AccountPasswordLockoutDurationMinutes do
  def decode(value, _options) do
    value
  end
end
