# NOTE: This file is auto generated by OpenAPI Generator
# https://openapi-generator.tech
# Do not edit this file manually.

defmodule DocuSign.Model.AccountSignatureProviders do
  @moduledoc """
  This resource provides information on the Standards Based Signature providers that have been provisioned for an account. 
  """

  alias DocuSign.Deserializer
  alias DocuSign.Model.AccountSignatureProvider

  defstruct [
    :signatureProviders
  ]

  @doc false
  defimpl Jason.Encoder, for: __MODULE__ do
    def encode(struct, opts) do
      struct
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> is_nil(v) end)
      |> Map.new()
      |> Jason.Encode.map(opts)
    end
  end

  @type t :: %__MODULE__{
          :signatureProviders => [AccountSignatureProvider.t()] | nil
        }

  def decode(value) do
    value
    |> Deserializer.deserialize(
      :signatureProviders,
      :list,
      AccountSignatureProvider
    )
    |> then(&struct(__MODULE__, &1))
  end
end
