# NOTE: This file is auto generated by OpenAPI Generator 6.4.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DocuSign.Model.AddressInformationInput do
  @moduledoc """
  Contains address input information.
  """

  @derive [Poison.Encoder]
  defstruct [
    :addressInformation,
    :displayLevelCode,
    :receiveInResponse
  ]

  @type t :: %__MODULE__{
          :addressInformation => DocuSign.Model.AddressInformation.t() | nil,
          :displayLevelCode => String.t() | nil,
          :receiveInResponse => String.t() | nil
        }
end

defimpl Poison.Decoder, for: DocuSign.Model.AddressInformationInput do
  import DocuSign.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:addressInformation, :struct, DocuSign.Model.AddressInformation, options)
  end
end
