# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DocuSign.Model.AppStoreProduct do
  @moduledoc """
  Contains information about an APP store product.
  """

  @derive [Poison.Encoder]
  defstruct [
    :marketPlace,
    :productId
  ]

  @type t :: %__MODULE__{
          :marketPlace => String.t() | nil,
          :productId => String.t() | nil
        }
end

defimpl Poison.Decoder, for: DocuSign.Model.AppStoreProduct do
  def decode(value, _options) do
    value
  end
end
