# NOTE: This file is auto generated by OpenAPI Generator
# https://openapi-generator.tech
# Do not edit this file manually.

defmodule DocuSign.Model.BillingChargeResponse do
  @moduledoc """
  Defines a billing charge response object.
  """

  alias DocuSign.Deserializer
  alias DocuSign.Model.BillingCharge

  @derive Jason.Encoder
  defstruct [
    :billingChargeItems
  ]

  @type t :: %__MODULE__{
          :billingChargeItems => [BillingCharge.t()] | nil
        }

  def decode(value) do
    value
    |> Deserializer.deserialize(
      :billingChargeItems,
      :list,
      BillingCharge
    )
  end
end
