# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DocuSign.Model.BillingPayment do
  @moduledoc """
  Contains information on a billing plan.
  """

  @derive [Poison.Encoder]
  defstruct [
    :amount,
    :invoiceId,
    :paymentId
  ]

  @type t :: %__MODULE__{
    :amount => String.t,
    :invoiceId => String.t,
    :paymentId => String.t
  }
end

defimpl Poison.Decoder, for: DocuSign.Model.BillingPayment do
  def decode(value, _options) do
    value
  end
end
