# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule DocuSign.Model.BillingChargeResponse do
  @moduledoc """
  Defines a billing charge response object.
  """

  @derive [Poison.Encoder]
  defstruct [
    :billingChargeItems
  ]

  @type t :: %__MODULE__{
    :billingChargeItems => [DocuSign.Model.BillingCharge.t] | nil
  }
end

defimpl Poison.Decoder, for: DocuSign.Model.BillingChargeResponse do
  import DocuSign.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:billingChargeItems, :list, DocuSign.Model.BillingCharge, options)
  end
end

