# NOTE: This file is auto generated by OpenAPI Generator 7.12.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DocuSign.Model.BillingInvoicesSummary do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :accountBalance,
    :billingInvoices,
    :currencyCode,
    :pastDueBalance,
    :paymentAllowed
  ]

  @type t :: %__MODULE__{
          :accountBalance => String.t() | nil,
          :billingInvoices => [DocuSign.Model.BillingInvoice.t()] | nil,
          :currencyCode => String.t() | nil,
          :pastDueBalance => String.t() | nil,
          :paymentAllowed => String.t() | nil
        }

  alias DocuSign.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:billingInvoices, :list, DocuSign.Model.BillingInvoice)
  end
end
