# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DocuSign.Model.BrandResources do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :createdByUserInfo,
    :createdDate,
    :modifiedByUserInfo,
    :modifiedDate,
    :modifiedTemplates,
    :resourcesContentType,
    :resourcesContentUri
  ]

  @type t :: %__MODULE__{
          :createdByUserInfo => UserInfo,
          :createdDate => String.t(),
          :modifiedByUserInfo => UserInfo,
          :modifiedDate => String.t(),
          :modifiedTemplates => [String.t()],
          :resourcesContentType => String.t(),
          :resourcesContentUri => String.t()
        }
end

defimpl Poison.Decoder, for: DocuSign.Model.BrandResources do
  import DocuSign.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:createdByUserInfo, :struct, DocuSign.Model.UserInfo, options)
    |> deserialize(:modifiedByUserInfo, :struct, DocuSign.Model.UserInfo, options)
  end
end
