# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule DocuSign.Model.BulkEnvelopeStatus do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :batchId,
    :batchSize,
    :bulkEnvelopes,
    :bulkEnvelopesBatchUri,
    :endPosition,
    :failed,
    :nextUri,
    :previousUri,
    :queued,
    :resultSetSize,
    :sent,
    :startPosition,
    :submittedDate,
    :totalSetSize
  ]

  @type t :: %__MODULE__{
    :batchId => String.t | nil,
    :batchSize => String.t | nil,
    :bulkEnvelopes => [DocuSign.Model.BulkEnvelope.t] | nil,
    :bulkEnvelopesBatchUri => String.t | nil,
    :endPosition => String.t | nil,
    :failed => String.t | nil,
    :nextUri => String.t | nil,
    :previousUri => String.t | nil,
    :queued => String.t | nil,
    :resultSetSize => String.t | nil,
    :sent => String.t | nil,
    :startPosition => String.t | nil,
    :submittedDate => String.t | nil,
    :totalSetSize => String.t | nil
  }
end

defimpl Poison.Decoder, for: DocuSign.Model.BulkEnvelopeStatus do
  import DocuSign.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:bulkEnvelopes, :list, DocuSign.Model.BulkEnvelope, options)
  end
end

