# NOTE: This file is auto generated by OpenAPI Generator
# https://openapi-generator.tech
# Do not edit this file manually.

defmodule DocuSign.Model.BulkSendingList do
  @moduledoc """
  This object contains the details for the bulk send list.
  """

  alias DocuSign.Deserializer
  alias DocuSign.Model.BulkSendingCopy

  defstruct [
    :bulkCopies,
    :listId,
    :name
  ]

  @doc false
  defimpl Jason.Encoder, for: __MODULE__ do
    def encode(struct, opts) do
      struct
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> is_nil(v) end)
      |> Map.new()
      |> Jason.Encode.map(opts)
    end
  end

  @type t :: %__MODULE__{
          :bulkCopies => [BulkSendingCopy.t()] | nil,
          :listId => String.t() | nil,
          :name => String.t() | nil
        }

  def decode(value) do
    value
    |> Deserializer.deserialize(
      :bulkCopies,
      :list,
      BulkSendingCopy
    )
    |> then(&struct(__MODULE__, &1))
  end
end
