# NOTE: This file is auto generated by OpenAPI Generator 7.12.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DocuSign.Model.BulkEnvelope do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :bulkRecipientRow,
    :bulkStatus,
    :email,
    :envelopeId,
    :envelopeUri,
    :errorDetails,
    :name,
    :submittedDateTime,
    :transactionId
  ]

  @type t :: %__MODULE__{
          :bulkRecipientRow => String.t() | nil,
          :bulkStatus => String.t() | nil,
          :email => String.t() | nil,
          :envelopeId => String.t() | nil,
          :envelopeUri => String.t() | nil,
          :errorDetails => DocuSign.Model.ErrorDetails.t() | nil,
          :name => String.t() | nil,
          :submittedDateTime => String.t() | nil,
          :transactionId => String.t() | nil
        }

  alias DocuSign.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:errorDetails, :struct, DocuSign.Model.ErrorDetails)
  end
end
