# NOTE: This file is auto generated by OpenAPI Generator
# https://openapi-generator.tech
# Do not edit this file manually.

defmodule DocuSign.Model.BulkSendBatchStatus do
  @moduledoc """
  Result of `getBulkSendBatchStatus`
  """

  alias DocuSign.Deserializer
  alias DocuSign.Model.BulkSendEnvelopesInfo
  alias DocuSign.Model.BulkSendErrorStatus

  defstruct [
    :action,
    :actionStatus,
    :batchId,
    :batchName,
    :batchSize,
    :bulkErrors,
    :envelopeIdOrTemplateId,
    :envelopesInfo,
    :envelopesUri,
    :failed,
    :mailingListId,
    :mailingListName,
    :ownerUserId,
    :queued,
    :resendsRemaining,
    :senderUserId,
    :sent,
    :submittedDate
  ]

  @doc false
  defimpl Jason.Encoder, for: __MODULE__ do
    def encode(struct, opts) do
      struct
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> is_nil(v) end)
      |> Map.new()
      |> Jason.Encode.map(opts)
    end
  end

  @type t :: %__MODULE__{
          :action => String.t() | nil,
          :actionStatus => String.t() | nil,
          :batchId => String.t() | nil,
          :batchName => String.t() | nil,
          :batchSize => String.t() | nil,
          :bulkErrors => [BulkSendErrorStatus.t()] | nil,
          :envelopeIdOrTemplateId => String.t() | nil,
          :envelopesInfo => BulkSendEnvelopesInfo.t() | nil,
          :envelopesUri => String.t() | nil,
          :failed => String.t() | nil,
          :mailingListId => String.t() | nil,
          :mailingListName => String.t() | nil,
          :ownerUserId => String.t() | nil,
          :queued => String.t() | nil,
          :resendsRemaining => String.t() | nil,
          :senderUserId => String.t() | nil,
          :sent => String.t() | nil,
          :submittedDate => String.t() | nil
        }

  def decode(value) do
    value
    |> Deserializer.deserialize(
      :bulkErrors,
      :list,
      BulkSendErrorStatus
    )
    |> Deserializer.deserialize(
      :envelopesInfo,
      :struct,
      BulkSendEnvelopesInfo
    )
    |> then(&struct(__MODULE__, &1))
  end
end
