# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DocuSign.Model.BulkRecipientsSummaryResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :bulkRecipients,
    :bulkRecipientsCount,
    :bulkRecipientsUri,
    :errorDetails
  ]

  @type t :: %__MODULE__{
    :bulkRecipients => [BulkRecipient],
    :bulkRecipientsCount => String.t,
    :bulkRecipientsUri => String.t,
    :errorDetails => [ErrorDetails]
  }
end

defimpl Poison.Decoder, for: DocuSign.Model.BulkRecipientsSummaryResponse do
  import DocuSign.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:bulkRecipients, :list, DocuSign.Model.BulkRecipient, options)
    |> deserialize(:errorDetails, :list, DocuSign.Model.ErrorDetails, options)
  end
end
