# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule DocuSign.Model.CommentsPublish do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :commentsToPublish
  ]

  @type t :: %__MODULE__{
    :commentsToPublish => [DocuSign.Model.CommentPublish.t] | nil
  }
end

defimpl Poison.Decoder, for: DocuSign.Model.CommentsPublish do
  import DocuSign.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:commentsToPublish, :list, DocuSign.Model.CommentPublish, options)
  end
end

