# NOTE: This file is auto generated by OpenAPI Generator 7.12.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DocuSign.Model.ConditionalRecipientRule do
  @moduledoc """
  A rule that defines a set of recipients and the conditions under which they will be used for the envelope.
  """

  alias DocuSign.Deserializer
  alias DocuSign.Model.ConditionalRecipientRuleCondition
  alias DocuSign.Model.RecipientGroup

  @derive Jason.Encoder
  defstruct [
    :conditions,
    :order,
    :recipientGroup,
    :recipientId
  ]

  @type t :: %__MODULE__{
          :conditions => [ConditionalRecipientRuleCondition.t()] | nil,
          :order => String.t() | nil,
          :recipientGroup => RecipientGroup.t() | nil,
          :recipientId => String.t() | nil
        }

  def decode(value) do
    value
    |> Deserializer.deserialize(
      :conditions,
      :list,
      ConditionalRecipientRuleCondition
    )
    |> Deserializer.deserialize(:recipientGroup, :struct, RecipientGroup)
  end
end
