# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DocuSign.Model.ConnectConfigurations do
  @moduledoc """
  Connect configurations
  """

  @derive [Poison.Encoder]
  defstruct [
    :allowEnvelopePublish,
    :allUsers,
    :configurationType,
    :connectId,
    :enableLog,
    :envelopeEvents,
    :includeCertificateOfCompletion,
    :includeCertSoapHeader,
    :includeDocumentFields,
    :includeDocuments,
    :includeEnvelopeVoidReason,
    :includeSenderAccountasCustomField,
    :includeTimeZoneInformation,
    :name,
    :recipientEvents,
    :requiresAcknowledgement,
    :signMessageWithX509Certificate,
    :soapNamespace,
    :urlToPublishTo,
    :userIds,
    :useSoapInterface
  ]

  @type t :: %__MODULE__{
    :allowEnvelopePublish => String.t,
    :allUsers => String.t,
    :configurationType => String.t,
    :connectId => String.t,
    :enableLog => String.t,
    :envelopeEvents => String.t,
    :includeCertificateOfCompletion => String.t,
    :includeCertSoapHeader => String.t,
    :includeDocumentFields => String.t,
    :includeDocuments => String.t,
    :includeEnvelopeVoidReason => String.t,
    :includeSenderAccountasCustomField => String.t,
    :includeTimeZoneInformation => String.t,
    :name => String.t,
    :recipientEvents => String.t,
    :requiresAcknowledgement => String.t,
    :signMessageWithX509Certificate => String.t,
    :soapNamespace => String.t,
    :urlToPublishTo => String.t,
    :userIds => String.t,
    :useSoapInterface => String.t
  }
end

defimpl Poison.Decoder, for: DocuSign.Model.ConnectConfigurations do
  def decode(value, _options) do
    value
  end
end
