# NOTE: This file is auto generated by OpenAPI Generator 6.4.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DocuSign.Model.ConsentDetails do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :consentKey,
    :deliveryMethod,
    :signerConsentStatus
  ]

  @type t :: %__MODULE__{
          :consentKey => String.t() | nil,
          :deliveryMethod => String.t() | nil,
          :signerConsentStatus => String.t() | nil
        }
end

defimpl Poison.Decoder, for: DocuSign.Model.ConsentDetails do
  def decode(value, _options) do
    value
  end
end
