# NOTE: This file is auto generated by OpenAPI Generator
# https://openapi-generator.tech
# Do not edit this file manually.

defmodule DocuSign.Model.ContactPhoneNumber do
  @moduledoc """
  Details about the phone numbers associated with a specific contact.
  """

  @derive Jason.Encoder
  defstruct [
    :phoneNumber,
    :phoneType
  ]

  @type t :: %__MODULE__{
          :phoneNumber => String.t() | nil,
          :phoneType => String.t() | nil
        }

  def decode(value) do
    value
  end
end
