# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule DocuSign.Model.CreditCardTypes do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :cardTypes
  ]

  @type t :: %__MODULE__{
    :cardTypes => [String.t] | nil
  }
end

defimpl Poison.Decoder, for: DocuSign.Model.CreditCardTypes do
  def decode(value, _options) do
    value
  end
end

