# NOTE: This file is auto generated by OpenAPI Generator
# https://openapi-generator.tech
# Do not edit this file manually.

defmodule DocuSign.Model.CurrencyFeatureSetPrice do
  @moduledoc """
  Information about the price and currency associated with the feature set. Reserved for internal Docusign use only.
  """

  defstruct [
    :currencyCode,
    :currencySymbol,
    :envelopeFee,
    :fixedFee,
    :seatFee
  ]

  @doc false
  defimpl Jason.Encoder, for: __MODULE__ do
    def encode(struct, opts) do
      struct
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> is_nil(v) end)
      |> Map.new()
      |> Jason.Encode.map(opts)
    end
  end

  @type t :: %__MODULE__{
          :currencyCode => String.t() | nil,
          :currencySymbol => String.t() | nil,
          :envelopeFee => String.t() | nil,
          :fixedFee => String.t() | nil,
          :seatFee => String.t() | nil
        }

  def decode(value) do
    struct(__MODULE__, value)
  end
end
