# NOTE: This file is auto generated by OpenAPI Generator 7.12.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DocuSign.Model.CurrencyPlanPrice do
  @moduledoc """

  """

  alias DocuSign.Deserializer
  alias DocuSign.Model.CreditCardTypes

  @derive Jason.Encoder
  defstruct [
    :currencyCode,
    :currencySymbol,
    :perSeatPrice,
    :supportIncidentFee,
    :supportPlanFee,
    :supportedCardTypes
  ]

  @type t :: %__MODULE__{
          :currencyCode => String.t() | nil,
          :currencySymbol => String.t() | nil,
          :perSeatPrice => String.t() | nil,
          :supportIncidentFee => String.t() | nil,
          :supportPlanFee => String.t() | nil,
          :supportedCardTypes => CreditCardTypes.t() | nil
        }

  def decode(value) do
    value
    |> Deserializer.deserialize(:supportedCardTypes, :struct, CreditCardTypes)
  end
end
