# NOTE: This file is auto generated by OpenAPI Generator
# https://openapi-generator.tech
# Do not edit this file manually.

defmodule DocuSign.Model.DirectDebitProcessorInformation do
  @moduledoc """
  Contains information about a bank that processes a customer's direct debit payments.
  """

  defstruct [
    :bankBranchCode,
    :bankCheckDigit,
    :bankCode,
    :bankName,
    :bankTransferAccountName,
    :bankTransferAccountNumber,
    :bankTransferType,
    :country,
    :email,
    :firstName,
    :iBAN,
    :lastName
  ]

  @doc false
  defimpl Jason.Encoder, for: __MODULE__ do
    def encode(struct, opts) do
      struct
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> is_nil(v) end)
      |> Map.new()
      |> Jason.Encode.map(opts)
    end
  end

  @type t :: %__MODULE__{
          :bankBranchCode => String.t() | nil,
          :bankCheckDigit => String.t() | nil,
          :bankCode => String.t() | nil,
          :bankName => String.t() | nil,
          :bankTransferAccountName => String.t() | nil,
          :bankTransferAccountNumber => String.t() | nil,
          :bankTransferType => String.t() | nil,
          :country => String.t() | nil,
          :email => String.t() | nil,
          :firstName => String.t() | nil,
          :iBAN => String.t() | nil,
          :lastName => String.t() | nil
        }

  def decode(value) do
    struct(__MODULE__, value)
  end
end
