# NOTE: This file is auto generated by OpenAPI Generator 7.12.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DocuSign.Model.DocGenFormFields do
  @moduledoc """
  A collection of document generation fields.
  """

  @derive Jason.Encoder
  defstruct [
    :docGenDocumentStatus,
    :docGenErrors,
    :docGenFormFieldList,
    :documentId
  ]

  @type t :: %__MODULE__{
          :docGenDocumentStatus => String.t() | nil,
          :docGenErrors => [DocuSign.Model.DocGenSyntaxError.t()] | nil,
          :docGenFormFieldList => [DocuSign.Model.DocGenFormField.t()] | nil,
          :documentId => String.t() | nil
        }

  alias DocuSign.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:docGenErrors, :list, DocuSign.Model.DocGenSyntaxError)
    |> Deserializer.deserialize(:docGenFormFieldList, :list, DocuSign.Model.DocGenFormField)
  end
end
