# NOTE: This file is auto generated by OpenAPI Generator
# https://openapi-generator.tech
# Do not edit this file manually.

defmodule DocuSign.Model.DocGenSyntaxError do
  @moduledoc """
  Describes document generation errors.
  """

  defstruct [
    :errorCode,
    :message,
    :tagIdentifier
  ]

  @doc false
  defimpl Jason.Encoder, for: __MODULE__ do
    def encode(struct, opts) do
      struct
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> is_nil(v) end)
      |> Map.new()
      |> Jason.Encode.map(opts)
    end
  end

  @type t :: %__MODULE__{
          :errorCode => String.t() | nil,
          :message => String.t() | nil,
          :tagIdentifier => String.t() | nil
        }

  def decode(value) do
    struct(__MODULE__, value)
  end
end
