# NOTE: This file is auto generated by OpenAPI Generator 6.4.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DocuSign.Model.DocGenFormField do
  @moduledoc false

  @derive [Poison.Encoder]
  defstruct [
    :label,
    :name,
    :required,
    :type,
    :value
  ]

  @type t :: %__MODULE__{
          :label => String.t() | nil,
          :name => String.t() | nil,
          :required => String.t() | nil,
          :type => String.t() | nil,
          :value => String.t() | nil
        }
end

defimpl Poison.Decoder, for: DocuSign.Model.DocGenFormField do
  def decode(value, _options) do
    value
  end
end
