# NOTE: This file is auto generated by OpenAPI Generator
# https://openapi-generator.tech
# Do not edit this file manually.

defmodule DocuSign.Model.DocumentVisibility do
  @moduledoc """
  This object configures a recipient's read/write access to a document.
  """

  alias DocuSign.Deserializer
  alias DocuSign.Model.ErrorDetails

  defstruct [
    :documentId,
    :errorDetails,
    :recipientId,
    :rights,
    :visible
  ]

  @doc false
  defimpl Jason.Encoder, for: __MODULE__ do
    def encode(struct, opts) do
      struct
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> is_nil(v) end)
      |> Map.new()
      |> Jason.Encode.map(opts)
    end
  end

  @type t :: %__MODULE__{
          :documentId => String.t() | nil,
          :errorDetails => ErrorDetails.t() | nil,
          :recipientId => String.t() | nil,
          :rights => String.t() | nil,
          :visible => String.t() | nil
        }

  def decode(value) do
    value
    |> Deserializer.deserialize(
      :errorDetails,
      :struct,
      ErrorDetails
    )
    |> then(&struct(__MODULE__, &1))
  end
end
