# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DocuSign.Model.DocumentFieldsInformation do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :documentFields
  ]

  @type t :: %__MODULE__{
          :documentFields => [DocuSign.Model.NameValue.t()] | nil
        }
end

defimpl Poison.Decoder, for: DocuSign.Model.DocumentFieldsInformation do
  import DocuSign.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:documentFields, :list, DocuSign.Model.NameValue, options)
  end
end
