# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule DocuSign.Model.DocumentResponsiveHtmlPreview do
  @moduledoc """
  This resource is used to create a responsive preview of a specific document.
  """

  @derive [Poison.Encoder]
  defstruct [
    :htmlDefinitions
  ]

  @type t :: %__MODULE__{
    :htmlDefinitions => [String.t] | nil
  }
end

defimpl Poison.Decoder, for: DocuSign.Model.DocumentResponsiveHtmlPreview do
  def decode(value, _options) do
    value
  end
end

