# NOTE: This file is auto generated by OpenAPI Generator
# https://openapi-generator.tech
# Do not edit this file manually.

defmodule DocuSign.Model.DocumentTemplateList do
  @moduledoc """

  """

  alias DocuSign.Deserializer
  alias DocuSign.Model.DocumentTemplate

  @derive Jason.Encoder
  defstruct [
    :documentTemplates
  ]

  @type t :: %__MODULE__{
          :documentTemplates => [DocumentTemplate.t()] | nil
        }

  def decode(value) do
    value
    |> Deserializer.deserialize(
      :documentTemplates,
      :list,
      DocumentTemplate
    )
  end
end
