# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule DocuSign.Model.EnvelopeTransferRules do
  @moduledoc """
  This resource provides methods that enable account administrators to create and manage envelope transfer rules.
  """

  @derive [Poison.Encoder]
  defstruct [
    :endPosition,
    :envelopeTransferRules,
    :nextUri,
    :previousUri,
    :resultSetSize,
    :startPosition,
    :totalSetSize
  ]

  @type t :: %__MODULE__{
    :endPosition => String.t | nil,
    :envelopeTransferRules => [DocuSign.Model.EnvelopeTransferRule.t] | nil,
    :nextUri => String.t | nil,
    :previousUri => String.t | nil,
    :resultSetSize => String.t | nil,
    :startPosition => String.t | nil,
    :totalSetSize => String.t | nil
  }
end

defimpl Poison.Decoder, for: DocuSign.Model.EnvelopeTransferRules do
  import DocuSign.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:envelopeTransferRules, :list, DocuSign.Model.EnvelopeTransferRule, options)
  end
end

