# NOTE: This file is auto generated by OpenAPI Generator 7.12.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DocuSign.Model.EnvelopeDocuments do
  @moduledoc """
  Envelope documents
  """

  @derive Jason.Encoder
  defstruct [
    :envelopeDocuments,
    :envelopeId
  ]

  @type t :: %__MODULE__{
          :envelopeDocuments => [DocuSign.Model.EnvelopeDocument.t()] | nil,
          :envelopeId => String.t() | nil
        }

  alias DocuSign.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:envelopeDocuments, :list, DocuSign.Model.EnvelopeDocument)
  end
end
