# NOTE: This file is auto generated by OpenAPI Generator
# https://openapi-generator.tech
# Do not edit this file manually.

defmodule DocuSign.Model.EnvelopeDocumentTabs do
  @moduledoc """
  Document tabs are tabs that are associated with a document rather than with a recipient.
  """

  alias DocuSign.Deserializer
  alias DocuSign.Model.Approve
  alias DocuSign.Model.Checkbox
  alias DocuSign.Model.CommentThread
  alias DocuSign.Model.CommissionCounty
  alias DocuSign.Model.CommissionExpiration
  alias DocuSign.Model.CommissionNumber
  alias DocuSign.Model.CommissionState
  alias DocuSign.Model.Company
  alias DocuSign.Model.DateSigned
  alias DocuSign.Model.Decline
  alias DocuSign.Model.Draw
  alias DocuSign.Model.EmailAddress
  alias DocuSign.Model.EnvelopeId
  alias DocuSign.Model.FirstName
  alias DocuSign.Model.FormulaTab
  alias DocuSign.Model.FullName
  alias DocuSign.Model.InitialHere
  alias DocuSign.Model.LastName
  alias DocuSign.Model.Notarize
  alias DocuSign.Model.NotarySeal
  alias DocuSign.Model.Note
  alias DocuSign.Model.Numerical
  alias DocuSign.Model.PhoneNumber
  alias DocuSign.Model.PolyLineOverlay
  alias DocuSign.Model.PrefillTabs
  alias DocuSign.Model.RadioGroup
  alias DocuSign.Model.SignerAttachment
  alias DocuSign.Model.SignHere
  alias DocuSign.Model.SmartSection
  alias DocuSign.Model.Ssn
  alias DocuSign.Model.TabGroup
  alias DocuSign.Model.Text
  alias DocuSign.Model.Title
  alias DocuSign.Model.View
  alias DocuSign.Model.Zip

  @derive Jason.Encoder
  defstruct [
    :approveTabs,
    :checkboxTabs,
    :commentThreadTabs,
    :commissionCountyTabs,
    :commissionExpirationTabs,
    :commissionNumberTabs,
    :commissionStateTabs,
    :companyTabs,
    :dateSignedTabs,
    :dateTabs,
    :declineTabs,
    :drawTabs,
    :emailAddressTabs,
    :emailTabs,
    :envelopeIdTabs,
    :firstNameTabs,
    :formulaTabs,
    :fullNameTabs,
    :initialHereTabs,
    :lastNameTabs,
    :listTabs,
    :notarizeTabs,
    :notarySealTabs,
    :noteTabs,
    :numberTabs,
    :numericalTabs,
    :phoneNumberTabs,
    :polyLineOverlayTabs,
    :prefillTabs,
    :radioGroupTabs,
    :signHereTabs,
    :signerAttachmentTabs,
    :smartSectionTabs,
    :ssnTabs,
    :tabGroups,
    :textTabs,
    :titleTabs,
    :viewTabs,
    :zipTabs
  ]

  @type t :: %__MODULE__{
          :approveTabs => [Approve.t()] | nil,
          :checkboxTabs => [Checkbox.t()] | nil,
          :commentThreadTabs => [CommentThread.t()] | nil,
          :commissionCountyTabs => [CommissionCounty.t()] | nil,
          :commissionExpirationTabs => [CommissionExpiration.t()] | nil,
          :commissionNumberTabs => [CommissionNumber.t()] | nil,
          :commissionStateTabs => [CommissionState.t()] | nil,
          :companyTabs => [Company.t()] | nil,
          :dateSignedTabs => [DateSigned.t()] | nil,
          :dateTabs => [Date.t()] | nil,
          :declineTabs => [Decline.t()] | nil,
          :drawTabs => [Draw.t()] | nil,
          :emailAddressTabs => [EmailAddress.t()] | nil,
          :emailTabs => [String.t()] | nil,
          :envelopeIdTabs => [EnvelopeId.t()] | nil,
          :firstNameTabs => [FirstName.t()] | nil,
          :formulaTabs => [FormulaTab.t()] | nil,
          :fullNameTabs => [FullName.t()] | nil,
          :initialHereTabs => [InitialHere.t()] | nil,
          :lastNameTabs => [LastName.t()] | nil,
          :listTabs => [DocuSign.Model.List.t()] | nil,
          :notarizeTabs => [Notarize.t()] | nil,
          :notarySealTabs => [NotarySeal.t()] | nil,
          :noteTabs => [Note.t()] | nil,
          :numberTabs => [number()] | nil,
          :numericalTabs => [Numerical.t()] | nil,
          :phoneNumberTabs => [PhoneNumber.t()] | nil,
          :polyLineOverlayTabs => [PolyLineOverlay.t()] | nil,
          :prefillTabs => PrefillTabs.t() | nil,
          :radioGroupTabs => [RadioGroup.t()] | nil,
          :signHereTabs => [SignHere.t()] | nil,
          :signerAttachmentTabs => [SignerAttachment.t()] | nil,
          :smartSectionTabs => [SmartSection.t()] | nil,
          :ssnTabs => [Ssn.t()] | nil,
          :tabGroups => [TabGroup.t()] | nil,
          :textTabs => [Text.t()] | nil,
          :titleTabs => [Title.t()] | nil,
          :viewTabs => [View.t()] | nil,
          :zipTabs => [Zip.t()] | nil
        }

  def decode(value) do
    value
    |> Deserializer.deserialize(
      :approveTabs,
      :list,
      Approve
    )
    |> Deserializer.deserialize(
      :checkboxTabs,
      :list,
      Checkbox
    )
    |> Deserializer.deserialize(
      :commentThreadTabs,
      :list,
      CommentThread
    )
    |> Deserializer.deserialize(
      :commissionCountyTabs,
      :list,
      CommissionCounty
    )
    |> Deserializer.deserialize(
      :commissionExpirationTabs,
      :list,
      CommissionExpiration
    )
    |> Deserializer.deserialize(
      :commissionNumberTabs,
      :list,
      CommissionNumber
    )
    |> Deserializer.deserialize(
      :commissionStateTabs,
      :list,
      CommissionState
    )
    |> Deserializer.deserialize(
      :companyTabs,
      :list,
      Company
    )
    |> Deserializer.deserialize(
      :dateSignedTabs,
      :list,
      DateSigned
    )
    |> Deserializer.deserialize(
      :declineTabs,
      :list,
      Decline
    )
    |> Deserializer.deserialize(
      :drawTabs,
      :list,
      Draw
    )
    |> Deserializer.deserialize(
      :emailAddressTabs,
      :list,
      EmailAddress
    )
    |> Deserializer.deserialize(
      :envelopeIdTabs,
      :list,
      EnvelopeId
    )
    |> Deserializer.deserialize(
      :firstNameTabs,
      :list,
      FirstName
    )
    |> Deserializer.deserialize(
      :formulaTabs,
      :list,
      FormulaTab
    )
    |> Deserializer.deserialize(
      :fullNameTabs,
      :list,
      FullName
    )
    |> Deserializer.deserialize(
      :initialHereTabs,
      :list,
      InitialHere
    )
    |> Deserializer.deserialize(
      :lastNameTabs,
      :list,
      LastName
    )
    |> Deserializer.deserialize(
      :listTabs,
      :list,
      DocuSign.Model.List
    )
    |> Deserializer.deserialize(
      :notarizeTabs,
      :list,
      Notarize
    )
    |> Deserializer.deserialize(
      :notarySealTabs,
      :list,
      NotarySeal
    )
    |> Deserializer.deserialize(
      :noteTabs,
      :list,
      Note
    )
    |> Deserializer.deserialize(
      :numericalTabs,
      :list,
      Numerical
    )
    |> Deserializer.deserialize(
      :phoneNumberTabs,
      :list,
      PhoneNumber
    )
    |> Deserializer.deserialize(
      :polyLineOverlayTabs,
      :list,
      PolyLineOverlay
    )
    |> Deserializer.deserialize(
      :prefillTabs,
      :struct,
      PrefillTabs
    )
    |> Deserializer.deserialize(
      :radioGroupTabs,
      :list,
      RadioGroup
    )
    |> Deserializer.deserialize(
      :signerAttachmentTabs,
      :list,
      SignerAttachment
    )
    |> Deserializer.deserialize(
      :signHereTabs,
      :list,
      SignHere
    )
    |> Deserializer.deserialize(
      :smartSectionTabs,
      :list,
      SmartSection
    )
    |> Deserializer.deserialize(
      :ssnTabs,
      :list,
      Ssn
    )
    |> Deserializer.deserialize(
      :tabGroups,
      :list,
      TabGroup
    )
    |> Deserializer.deserialize(
      :textTabs,
      :list,
      Text
    )
    |> Deserializer.deserialize(
      :titleTabs,
      :list,
      Title
    )
    |> Deserializer.deserialize(
      :viewTabs,
      :list,
      View
    )
    |> Deserializer.deserialize(
      :zipTabs,
      :list,
      Zip
    )
  end
end
