# NOTE: This file is auto generated by OpenAPI Generator
# https://openapi-generator.tech
# Do not edit this file manually.

defmodule DocuSign.Model.EnvelopeCustomMetadata do
  @moduledoc """

  """

  alias DocuSign.Deserializer
  alias DocuSign.Model.NameValue

  @derive Jason.Encoder
  defstruct [
    :envelopeCustomMetadataDetails
  ]

  @type t :: %__MODULE__{
          :envelopeCustomMetadataDetails => [NameValue.t()] | nil
        }

  def decode(value) do
    value
    |> Deserializer.deserialize(
      :envelopeCustomMetadataDetails,
      :list,
      NameValue
    )
  end
end
