# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule DocuSign.Model.EnvelopePublishTransactionErrorRollup do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :count,
    :errorType
  ]

  @type t :: %__MODULE__{
    :count => String.t | nil,
    :errorType => String.t | nil
  }
end

defimpl Poison.Decoder, for: DocuSign.Model.EnvelopePublishTransactionErrorRollup do
  def decode(value, _options) do
    value
  end
end

