# NOTE: This file is auto generated by OpenAPI Generator
# https://openapi-generator.tech
# Do not edit this file manually.

defmodule DocuSign.Model.EnvelopeViewTaggerSettings do
  @moduledoc """

  """

  alias DocuSign.Deserializer
  alias DocuSign.Model.PaletteSettings

  defstruct [
    :paletteDefault,
    :paletteSections,
    :paletteSettings
  ]

  @doc false
  defimpl Jason.Encoder, for: __MODULE__ do
    def encode(struct, opts) do
      struct
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> is_nil(v) end)
      |> Map.new()
      |> Jason.Encode.map(opts)
    end
  end

  @type t :: %__MODULE__{
          :paletteDefault => String.t() | nil,
          :paletteSections => String.t() | nil,
          :paletteSettings => PaletteSettings.t() | nil
        }

  def decode(value) do
    value
    |> Deserializer.deserialize(
      :paletteSettings,
      :struct,
      PaletteSettings
    )
    |> then(&struct(__MODULE__, &1))
  end
end
