# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule DocuSign.Model.EnvelopeEvent do
  @moduledoc """
  For which envelope events should your webhook be called?
  """

  @derive [Poison.Encoder]
  defstruct [
    :envelopeEventStatusCode,
    :includeDocuments
  ]

  @type t :: %__MODULE__{
    :envelopeEventStatusCode => String.t | nil,
    :includeDocuments => String.t | nil
  }
end

defimpl Poison.Decoder, for: DocuSign.Model.EnvelopeEvent do
  def decode(value, _options) do
    value
  end
end

