# NOTE: This file is auto generated by OpenAPI Generator 7.12.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DocuSign.Model.EnvelopeViewDocumentSettings do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :showEditDocuments,
    :showEditDocumentVisibility,
    :showEditPages,
    :showSaveAsDocumentCustomField
  ]

  @type t :: %__MODULE__{
          :showEditDocuments => String.t() | nil,
          :showEditDocumentVisibility => String.t() | nil,
          :showEditPages => String.t() | nil,
          :showSaveAsDocumentCustomField => String.t() | nil
        }

  def decode(value) do
    value
  end
end
