# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DocuSign.Model.EnvelopeDocumentVisibility do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :documentVisibility
  ]

  @type t :: %__MODULE__{
          :documentVisibility => [DocumentVisibility]
        }
end

defimpl Poison.Decoder, for: DocuSign.Model.EnvelopeDocumentVisibility do
  import DocuSign.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:documentVisibility, :list, DocuSign.Model.DocumentVisibility, options)
  end
end
