# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule DocuSign.Model.ExternalPrimaryAccountRecipientAuthRequirements do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :accessCode,
    :idVerification,
    :kba,
    :phone
  ]

  @type t :: %__MODULE__{
    :accessCode => String.t | nil,
    :idVerification => String.t | nil,
    :kba => String.t | nil,
    :phone => String.t | nil
  }
end

defimpl Poison.Decoder, for: DocuSign.Model.ExternalPrimaryAccountRecipientAuthRequirements do
  def decode(value, _options) do
    value
  end
end

