# NOTE: This file is auto generated by OpenAPI Generator 7.12.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DocuSign.Model.FavoriteTemplatesContentItem do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :errorDetails,
    :favoritedDate,
    :templateId
  ]

  @type t :: %__MODULE__{
          :errorDetails => DocuSign.Model.ErrorDetails.t() | nil,
          :favoritedDate => String.t() | nil,
          :templateId => String.t() | nil
        }

  alias DocuSign.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:errorDetails, :struct, DocuSign.Model.ErrorDetails)
  end
end
