# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DocuSign.Model.FeatureSet do
  @moduledoc false

  @derive [Poison.Encoder]
  defstruct [
    :currencyFeatureSetPrices,
    :envelopeFee,
    :featureSetId,
    :fixedFee,
    :is21CFRPart11,
    :isActive,
    :isEnabled,
    :name,
    :seatFee
  ]

  @type t :: %__MODULE__{
          :currencyFeatureSetPrices => [CurrencyFeatureSetPrice],
          :envelopeFee => String.t(),
          :featureSetId => String.t(),
          :fixedFee => String.t(),
          :is21CFRPart11 => String.t(),
          :isActive => String.t(),
          :isEnabled => String.t(),
          :name => String.t(),
          :seatFee => String.t()
        }
end

defimpl Poison.Decoder, for: DocuSign.Model.FeatureSet do
  import DocuSign.Deserializer

  def decode(value, options) do
    value
    |> deserialize(
      :currencyFeatureSetPrices,
      :list,
      DocuSign.Model.CurrencyFeatureSetPrice,
      options
    )
  end
end
