# NOTE: This file is auto generated by OpenAPI Generator
# https://openapi-generator.tech
# Do not edit this file manually.

defmodule DocuSign.Model.Filter do
  @moduledoc """
  Use this object to create a filtered view of the items in a folder.
  """

  @derive Jason.Encoder
  defstruct [
    :actionRequired,
    :expires,
    :folderIds,
    :fromDateTime,
    :isTemplate,
    :order,
    :orderBy,
    :searchTarget,
    :searchText,
    :status,
    :toDateTime
  ]

  @type t :: %__MODULE__{
          :actionRequired => String.t() | nil,
          :expires => String.t() | nil,
          :folderIds => String.t() | nil,
          :fromDateTime => String.t() | nil,
          :isTemplate => String.t() | nil,
          :order => String.t() | nil,
          :orderBy => String.t() | nil,
          :searchTarget => String.t() | nil,
          :searchText => String.t() | nil,
          :status => String.t() | nil,
          :toDateTime => String.t() | nil
        }

  def decode(value) do
    value
  end
end
