# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule DocuSign.Model.GroupBrands do
  @moduledoc """
  If your account includes multiple signing brands, you can use the groups functionality to assign different brands to different groups. This resource enables you to manage group brands.
  """

  @derive [Poison.Encoder]
  defstruct [
    :recipientBrandIdDefault,
    :senderBrandIdDefault,
    :brandOptions
  ]

  @type t :: %__MODULE__{
    :recipientBrandIdDefault => String.t | nil,
    :senderBrandIdDefault => String.t | nil,
    :brandOptions => [DocuSign.Model.Brand.t] | nil
  }
end

defimpl Poison.Decoder, for: DocuSign.Model.GroupBrands do
  import DocuSign.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:brandOptions, :list, DocuSign.Model.Brand, options)
  end
end

