# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DocuSign.Model.IdCheckInformationInput do
  @moduledoc """
  A complex element that contains input information related to a recipient ID check. It can include the following information.  addressInformationInput: Used to set recipient address information and consists of:  * addressInformation: consists of six elements, with stree2 and zipPlus4 being optional. The elements are: street1, street2, city, state, zip, zipPlus4. The maximum length of each element is: street1/street2 &#x3D; 150 characters, city &#x3D; 50 characters, state &#x3D; 2 characters, and zip/zipPlus4 &#x3D; 20 characters. * displayLevelCode: Specifies the display level for the recipient. Values are: ReadOnly, Editable, or DoNotDisplay. * receiveInResponse: A Boolean element that specifies if the information needs to be returned in the response.  dobInformationInput: Used to set recipient date of birth information and consists of:  * dateOfBirth: Specifies the recipient&#39;s date, month and year of birth. * displayLevelCode: Specifies the display level for the recipient. Values are: ReadOnly, Editable, or DoNotDisplay. * receiveInResponse: A Boolean element that specifies if the information needs to be returned in the response.  ssn4InformationInput: Used to set the last four digits of the recipient&#39;s SSN information and consists of:  * ssn4: Specifies the last four digits of the recipient&#39;s SSN. * displayLevelCode: Specifies the display level for the recipient. Values are: ReadOnly, Editable, or DoNotDisplay. * receiveInResponse: A Boolean element that specifies if the information needs to be returned in the response.  ssn9InformationInput: Used to set the recipient&#39;s SSN information. Note that the ssn9 information can never be returned in the response. The ssn9 input consists of:  * ssn9: Specifies the recipient&#39;s SSN. * displayLevelCode: Specifies the display level for the recipient. Values are: ReadOnly, Editable, or DoNotDisplay.
  """

  @derive [Poison.Encoder]
  defstruct [
    :addressInformationInput,
    :dobInformationInput,
    :ssn4InformationInput,
    :ssn9InformationInput
  ]

  @type t :: %__MODULE__{
          :addressInformationInput => AddressInformationInput,
          :dobInformationInput => DobInformationInput,
          :ssn4InformationInput => Ssn4InformationInput,
          :ssn9InformationInput => Ssn9InformationInput
        }
end

defimpl Poison.Decoder, for: DocuSign.Model.IdCheckInformationInput do
  import DocuSign.Deserializer

  def decode(value, options) do
    value
    |> deserialize(
      :addressInformationInput,
      :struct,
      DocuSign.Model.AddressInformationInput,
      options
    )
    |> deserialize(:dobInformationInput, :struct, DocuSign.Model.DobInformationInput, options)
    |> deserialize(:ssn4InformationInput, :struct, DocuSign.Model.Ssn4InformationInput, options)
    |> deserialize(:ssn9InformationInput, :struct, DocuSign.Model.Ssn9InformationInput, options)
  end
end
