# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule DocuSign.Model.IdentityVerifications do
  @moduledoc """
  Identity Verification enables you to verify a signer's identity before they can access a document. The `IdentityVerifications` resource provides a method that enables you to list the workflows that are available to an account.
  """

  @derive [Poison.Encoder]
  defstruct [
    :identityVerification
  ]

  @type t :: %__MODULE__{
    :identityVerification => [DocuSign.Model.AccountIdentityVerificationWorkflow.t] | nil
  }
end

defimpl Poison.Decoder, for: DocuSign.Model.IdentityVerifications do
  import DocuSign.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:identityVerification, :list, DocuSign.Model.AccountIdentityVerificationWorkflow, options)
  end
end

