# NOTE: This file is auto generated by OpenAPI Generator
# https://openapi-generator.tech
# Do not edit this file manually.

defmodule DocuSign.Model.ListCustomField do
  @moduledoc """
  This object represents a list custom field from which envelope creators and senders can select custom data.
  """

  alias DocuSign.Deserializer
  alias DocuSign.Model.ErrorDetails

  defstruct [
    :configurationType,
    :errorDetails,
    :fieldId,
    :listItems,
    :name,
    :required,
    :show,
    :value
  ]

  @doc false
  defimpl Jason.Encoder, for: __MODULE__ do
    def encode(struct, opts) do
      struct
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> is_nil(v) end)
      |> Map.new()
      |> Jason.Encode.map(opts)
    end
  end

  @type t :: %__MODULE__{
          :configurationType => String.t() | nil,
          :errorDetails => ErrorDetails.t() | nil,
          :fieldId => String.t() | nil,
          :listItems => [String.t()] | nil,
          :name => String.t() | nil,
          :required => String.t() | nil,
          :show => String.t() | nil,
          :value => String.t() | nil
        }

  def decode(value) do
    value
    |> Deserializer.deserialize(
      :errorDetails,
      :struct,
      ErrorDetails
    )
    |> then(&struct(__MODULE__, &1))
  end
end
