# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule DocuSign.Model.LoginInformation do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :apiPassword,
    :loginAccounts
  ]

  @type t :: %__MODULE__{
    :apiPassword => String.t | nil,
    :loginAccounts => [DocuSign.Model.LoginAccount.t] | nil
  }
end

defimpl Poison.Decoder, for: DocuSign.Model.LoginInformation do
  import DocuSign.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:loginAccounts, :list, DocuSign.Model.LoginAccount, options)
  end
end

