# NOTE: This file is auto generated by OpenAPI Generator
# https://openapi-generator.tech
# Do not edit this file manually.

defmodule DocuSign.Model.LoginInformation do
  @moduledoc """

  """

  alias DocuSign.Deserializer
  alias DocuSign.Model.LoginAccount

  defstruct [
    :apiPassword,
    :loginAccounts
  ]

  @doc false
  defimpl Jason.Encoder, for: __MODULE__ do
    def encode(struct, opts) do
      struct
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> is_nil(v) end)
      |> Map.new()
      |> Jason.Encode.map(opts)
    end
  end

  @type t :: %__MODULE__{
          :apiPassword => String.t() | nil,
          :loginAccounts => [LoginAccount.t()] | nil
        }

  def decode(value) do
    value
    |> Deserializer.deserialize(
      :loginAccounts,
      :list,
      LoginAccount
    )
    |> then(&struct(__MODULE__, &1))
  end
end
