# NOTE: This file is auto generated by OpenAPI Generator 7.12.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DocuSign.Model.LoginAccount do
  @moduledoc """

  """

  alias DocuSign.Deserializer
  alias DocuSign.Model.NameValue

  @derive Jason.Encoder
  defstruct [
    :accountId,
    :accountIdGuid,
    :baseUrl,
    :email,
    :isDefault,
    :loginAccountSettings,
    :loginUserSettings,
    :name,
    :siteDescription,
    :userId,
    :userName
  ]

  @type t :: %__MODULE__{
          :accountId => String.t() | nil,
          :accountIdGuid => String.t() | nil,
          :baseUrl => String.t() | nil,
          :email => String.t() | nil,
          :isDefault => String.t() | nil,
          :loginAccountSettings => [NameValue.t()] | nil,
          :loginUserSettings => [NameValue.t()] | nil,
          :name => String.t() | nil,
          :siteDescription => String.t() | nil,
          :userId => String.t() | nil,
          :userName => String.t() | nil
        }

  def decode(value) do
    value
    |> Deserializer.deserialize(:loginAccountSettings, :list, NameValue)
    |> Deserializer.deserialize(:loginUserSettings, :list, NameValue)
  end
end
