# NOTE: This file is auto generated by OpenAPI Generator 7.12.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DocuSign.Model.MemberGroupSharedItem do
  @moduledoc """
  Information about items shared among groups.
  """

  @derive Jason.Encoder
  defstruct [
    :errorDetails,
    :group,
    :shared
  ]

  @type t :: %__MODULE__{
          :errorDetails => DocuSign.Model.ErrorDetails.t() | nil,
          :group => DocuSign.Model.Group.t() | nil,
          :shared => String.t() | nil
        }

  alias DocuSign.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:errorDetails, :struct, DocuSign.Model.ErrorDetails)
    |> Deserializer.deserialize(:group, :struct, DocuSign.Model.Group)
  end
end
