# NOTE: This file is auto generated by OpenAPI Generator 7.12.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DocuSign.Model.NotificationDefaultSettings do
  @moduledoc """
  Contains details about the default notification settings for the envelope notifications that senders and signers receive.
  """

  alias DocuSign.Deserializer
  alias DocuSign.Model.SenderEmailNotifications
  alias DocuSign.Model.SignerEmailNotifications

  @derive Jason.Encoder
  defstruct [
    :senderEmailNotifications,
    :signerEmailNotifications
  ]

  @type t :: %__MODULE__{
          :senderEmailNotifications => SenderEmailNotifications.t() | nil,
          :signerEmailNotifications => SignerEmailNotifications.t() | nil
        }

  def decode(value) do
    value
    |> Deserializer.deserialize(
      :senderEmailNotifications,
      :struct,
      SenderEmailNotifications
    )
    |> Deserializer.deserialize(
      :signerEmailNotifications,
      :struct,
      SignerEmailNotifications
    )
  end
end
