# NOTE: This file is auto generated by OpenAPI Generator 7.12.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DocuSign.Model.PageRequest do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :password,
    :rotate
  ]

  @type t :: %__MODULE__{
          :password => String.t() | nil,
          :rotate => String.t() | nil
        }

  def decode(value) do
    value
  end
end
