# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DocuSign.Model.PermissionProfileInformation do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :permissionProfiles
  ]

  @type t :: %__MODULE__{
          :permissionProfiles => [AccountPermissionProfiles]
        }
end

defimpl Poison.Decoder, for: DocuSign.Model.PermissionProfileInformation do
  import DocuSign.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:permissionProfiles, :list, DocuSign.Model.AccountPermissionProfiles, options)
  end
end
