# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DocuSign.Model.PlanInformation do
  @moduledoc """
  An object used to identify the features and attributes of the account being created.
  """

  @derive [Poison.Encoder]
  defstruct [
    :addOns,
    :currencyCode,
    :freeTrialDaysOverride,
    :planFeatureSets,
    :planId,
    :recipientDomains
  ]

  @type t :: %__MODULE__{
          :addOns => [DocuSign.Model.AddOn.t()] | nil,
          :currencyCode => String.t() | nil,
          :freeTrialDaysOverride => String.t() | nil,
          :planFeatureSets => [DocuSign.Model.FeatureSet.t()] | nil,
          :planId => String.t() | nil,
          :recipientDomains => [DocuSign.Model.RecipientDomain.t()] | nil
        }
end

defimpl Poison.Decoder, for: DocuSign.Model.PlanInformation do
  import DocuSign.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:addOns, :list, DocuSign.Model.AddOn, options)
    |> deserialize(:planFeatureSets, :list, DocuSign.Model.FeatureSet, options)
    |> deserialize(:recipientDomains, :list, DocuSign.Model.RecipientDomain, options)
  end
end
