# NOTE: This file is auto generated by OpenAPI Generator
# https://openapi-generator.tech
# Do not edit this file manually.

defmodule DocuSign.Model.PowerFormsFormDataResponse do
  @moduledoc """

  """

  alias DocuSign.Deserializer
  alias DocuSign.Model.PowerFormFormDataEnvelope

  @derive Jason.Encoder
  defstruct [
    :envelopes
  ]

  @type t :: %__MODULE__{
          :envelopes => [PowerFormFormDataEnvelope.t()] | nil
        }

  def decode(value) do
    value
    |> Deserializer.deserialize(
      :envelopes,
      :list,
      PowerFormFormDataEnvelope
    )
  end
end
