# NOTE: This file is auto generated by OpenAPI Generator 6.4.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DocuSign.Model.PowerFormData do
  @moduledoc """
  Data that recipients have entered in PowerForm fields.
  """

  @derive [Poison.Encoder]
  defstruct [
    :envelopeId,
    :recipients
  ]

  @type t :: %__MODULE__{
          :envelopeId => String.t() | nil,
          :recipients => [DocuSign.Model.PowerFormFormDataRecipient.t()] | nil
        }
end

defimpl Poison.Decoder, for: DocuSign.Model.PowerFormData do
  import DocuSign.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:recipients, :list, DocuSign.Model.PowerFormFormDataRecipient, options)
  end
end
