# NOTE: This file is auto generated by OpenAPI Generator 7.12.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DocuSign.Model.RecipientRouting do
  @moduledoc """
  Describes the recipient routing rules.
  """

  alias DocuSign.Deserializer
  alias DocuSign.Model.RecipientRules

  @derive Jason.Encoder
  defstruct [
    :rules
  ]

  @type t :: %__MODULE__{
          :rules => RecipientRules.t() | nil
        }

  def decode(value) do
    value
    |> Deserializer.deserialize(:rules, :struct, RecipientRules)
  end
end
