# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DocuSign.Model.RecipientDomain do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :active,
    :domainCode,
    :domainName,
    :recipientDomainId
  ]

  @type t :: %__MODULE__{
          :active => String.t(),
          :domainCode => String.t(),
          :domainName => String.t(),
          :recipientDomainId => String.t()
        }
end

defimpl Poison.Decoder, for: DocuSign.Model.RecipientDomain do
  def decode(value, _options) do
    value
  end
end
