# NOTE: This file is auto generated by OpenAPI Generator 7.12.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DocuSign.Model.RecipientSignatureProviderOptions do
  @moduledoc """
  Option settings for the signature provider. Different providers require or use different options. [The current provider list and the options they require.](/docs/esign-rest-api/esign101/concepts/standards-based-signatures/)
  """

  alias DocuSign.Deserializer
  alias DocuSign.Model.PropertyMetadata

  @derive Jason.Encoder
  defstruct [
    :cpfNumber,
    :cpfNumberMetadata,
    :oneTimePassword,
    :oneTimePasswordMetadata,
    :signerRole,
    :signerRoleMetadata,
    :sms,
    :smsMetadata
  ]

  @type t :: %__MODULE__{
          :cpfNumber => String.t() | nil,
          :cpfNumberMetadata => PropertyMetadata.t() | nil,
          :oneTimePassword => String.t() | nil,
          :oneTimePasswordMetadata => PropertyMetadata.t() | nil,
          :signerRole => String.t() | nil,
          :signerRoleMetadata => PropertyMetadata.t() | nil,
          :sms => String.t() | nil,
          :smsMetadata => PropertyMetadata.t() | nil
        }

  def decode(value) do
    value
    |> Deserializer.deserialize(:cpfNumberMetadata, :struct, PropertyMetadata)
    |> Deserializer.deserialize(
      :oneTimePasswordMetadata,
      :struct,
      PropertyMetadata
    )
    |> Deserializer.deserialize(:signerRoleMetadata, :struct, PropertyMetadata)
    |> Deserializer.deserialize(:smsMetadata, :struct, PropertyMetadata)
  end
end
