# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule DocuSign.Model.RecipientEmailNotification do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :emailBody,
    :emailBodyMetadata,
    :emailSubject,
    :emailSubjectMetadata,
    :supportedLanguage,
    :supportedLanguageMetadata
  ]

  @type t :: %__MODULE__{
    :emailBody => String.t | nil,
    :emailBodyMetadata => DocuSign.Model.PropertyMetadata.t | nil,
    :emailSubject => String.t | nil,
    :emailSubjectMetadata => DocuSign.Model.PropertyMetadata.t | nil,
    :supportedLanguage => String.t | nil,
    :supportedLanguageMetadata => DocuSign.Model.PropertyMetadata.t | nil
  }
end

defimpl Poison.Decoder, for: DocuSign.Model.RecipientEmailNotification do
  import DocuSign.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:emailBodyMetadata, :struct, DocuSign.Model.PropertyMetadata, options)
    |> deserialize(:emailSubjectMetadata, :struct, DocuSign.Model.PropertyMetadata, options)
    |> deserialize(:supportedLanguageMetadata, :struct, DocuSign.Model.PropertyMetadata, options)
  end
end

