# NOTE: This file is auto generated by OpenAPI Generator 7.12.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DocuSign.Model.RecipientAttachment do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :attachmentId,
    :attachmentType,
    :data,
    :label,
    :name,
    :remoteUrl
  ]

  @type t :: %__MODULE__{
          :attachmentId => String.t() | nil,
          :attachmentType => String.t() | nil,
          :data => String.t() | nil,
          :label => String.t() | nil,
          :name => String.t() | nil,
          :remoteUrl => String.t() | nil
        }

  def decode(value) do
    value
  end
end
