# NOTE: This file is auto generated by OpenAPI Generator
# https://openapi-generator.tech
# Do not edit this file manually.

defmodule DocuSign.Model.RecipientProofFile do
  @moduledoc """
  The proof file of the recipient. [ID Evidence](/docs/idevidence-api/) uses proof files to store the identification data that recipients submit when verifying their ID with [ID Verification](/docs/esign-rest-api/esign101/concepts/documents/)
  """

  @derive Jason.Encoder
  defstruct [
    :hasIdentityAttempts,
    :isInProofFile
  ]

  @type t :: %__MODULE__{
          :hasIdentityAttempts => String.t() | nil,
          :isInProofFile => String.t() | nil
        }

  def decode(value) do
    value
  end
end
