# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule DocuSign.Model.RecipientAttachment do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :attachmentId,
    :attachmentType,
    :data,
    :label,
    :name,
    :remoteUrl
  ]

  @type t :: %__MODULE__{
    :attachmentId => String.t | nil,
    :attachmentType => String.t | nil,
    :data => String.t | nil,
    :label => String.t | nil,
    :name => String.t | nil,
    :remoteUrl => String.t | nil
  }
end

defimpl Poison.Decoder, for: DocuSign.Model.RecipientAttachment do
  def decode(value, _options) do
    value
  end
end

