# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DocuSign.Model.ReferralInformation do
  @moduledoc """
  A complex type that contains the following information for entering referral and discount information. The following items are included in the referral information (all string content): enableSupport, includedSeats, saleDiscountPercent, saleDiscountAmount, saleDiscountFixedAmount, saleDiscountPeriods, saleDiscountSeatPriceOverride, planStartMonth, referralCode, referrerName, advertisementId, publisherId, shopperId, promoCode, groupMemberId, idType, and industry  **Note:** saleDiscountPercent, saleDiscountAmount, saleDiscountFixedAmount, saleDiscountPeriods, and saleDiscountSeatPriceOverride are reserved for DocuSign use only.
  """

  @derive [Poison.Encoder]
  defstruct [
    :advertisementId,
    :enableSupport,
    :externalOrgId,
    :groupMemberId,
    :idType,
    :includedSeats,
    :industry,
    :planStartMonth,
    :promoCode,
    :publisherId,
    :referralCode,
    :referrerName,
    :saleDiscountAmount,
    :saleDiscountFixedAmount,
    :saleDiscountPercent,
    :saleDiscountPeriods,
    :saleDiscountSeatPriceOverride,
    :shopperId
  ]

  @type t :: %__MODULE__{
          :advertisementId => String.t() | nil,
          :enableSupport => String.t() | nil,
          :externalOrgId => String.t() | nil,
          :groupMemberId => String.t() | nil,
          :idType => String.t() | nil,
          :includedSeats => String.t() | nil,
          :industry => String.t() | nil,
          :planStartMonth => String.t() | nil,
          :promoCode => String.t() | nil,
          :publisherId => String.t() | nil,
          :referralCode => String.t() | nil,
          :referrerName => String.t() | nil,
          :saleDiscountAmount => String.t() | nil,
          :saleDiscountFixedAmount => String.t() | nil,
          :saleDiscountPercent => String.t() | nil,
          :saleDiscountPeriods => String.t() | nil,
          :saleDiscountSeatPriceOverride => String.t() | nil,
          :shopperId => String.t() | nil
        }
end

defimpl Poison.Decoder, for: DocuSign.Model.ReferralInformation do
  def decode(value, _options) do
    value
  end
end
