# NOTE: This file is auto generated by OpenAPI Generator
# https://openapi-generator.tech
# Do not edit this file manually.

defmodule DocuSign.Model.ScheduledSending do
  @moduledoc """
  A complex element that specifies the scheduled sending settings for the envelope.
  """

  alias DocuSign.Deserializer
  alias DocuSign.Model.EnvelopeDelayRule

  defstruct [
    :bulkListId,
    :resumeDate,
    :rules,
    :status
  ]

  @doc false
  defimpl Jason.Encoder, for: __MODULE__ do
    def encode(struct, opts) do
      struct
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> is_nil(v) end)
      |> Map.new()
      |> Jason.Encode.map(opts)
    end
  end

  @type t :: %__MODULE__{
          :bulkListId => String.t() | nil,
          :resumeDate => String.t() | nil,
          :rules => [EnvelopeDelayRule.t()] | nil,
          :status => String.t() | nil
        }

  def decode(value) do
    value
    |> Deserializer.deserialize(
      :rules,
      :list,
      EnvelopeDelayRule
    )
    |> then(&struct(__MODULE__, &1))
  end
end
