# NOTE: This file is auto generated by OpenAPI Generator 7.12.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DocuSign.Model.SealIdentifier do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :sealDisplayName,
    :sealName
  ]

  @type t :: %__MODULE__{
          :sealDisplayName => String.t() | nil,
          :sealName => String.t() | nil
        }

  def decode(value) do
    value
  end
end
