# NOTE: This file is auto generated by OpenAPI Generator
# https://openapi-generator.tech
# Do not edit this file manually.

defmodule DocuSign.Model.SignatureGroup do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :groupId,
    :groupName,
    :rights
  ]

  @type t :: %__MODULE__{
          :groupId => String.t() | nil,
          :groupName => String.t() | nil,
          :rights => String.t() | nil
        }

  def decode(value) do
    value
  end
end
