# NOTE: This file is auto generated by OpenAPI Generator
# https://openapi-generator.tech
# Do not edit this file manually.

defmodule DocuSign.Model.SigningGroup do
  @moduledoc """
  Contains details about a signing group. Signing groups enable you to send an envelope to a predefined group of recipients and have any one member of the group sign your documents. When you send an envelope to a signing group, anyone in the group can open it and sign it with their own signature.
  """

  alias DocuSign.Deserializer
  alias DocuSign.Model.ErrorDetails
  alias DocuSign.Model.SigningGroupUser

  defstruct [
    :created,
    :createdBy,
    :errorDetails,
    :groupEmail,
    :groupName,
    :groupType,
    :modified,
    :modifiedBy,
    :signingGroupId,
    :users
  ]

  @doc false
  defimpl Jason.Encoder, for: __MODULE__ do
    def encode(struct, opts) do
      struct
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> is_nil(v) end)
      |> Map.new()
      |> Jason.Encode.map(opts)
    end
  end

  @type t :: %__MODULE__{
          :created => String.t() | nil,
          :createdBy => String.t() | nil,
          :errorDetails => ErrorDetails.t() | nil,
          :groupEmail => String.t() | nil,
          :groupName => String.t() | nil,
          :groupType => String.t() | nil,
          :modified => String.t() | nil,
          :modifiedBy => String.t() | nil,
          :signingGroupId => String.t() | nil,
          :users => [SigningGroupUser.t()] | nil
        }

  def decode(value) do
    value
    |> Deserializer.deserialize(
      :errorDetails,
      :struct,
      ErrorDetails
    )
    |> Deserializer.deserialize(
      :users,
      :list,
      SigningGroupUser
    )
    |> then(&struct(__MODULE__, &1))
  end
end
