# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule DocuSign.Model.SmartSectionAnchorPosition do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :pageNumber,
    :xPosition,
    :yPosition
  ]

  @type t :: %__MODULE__{
    :pageNumber => integer() | nil,
    :xPosition => float() | nil,
    :yPosition => float() | nil
  }
end

defimpl Poison.Decoder, for: DocuSign.Model.SmartSectionAnchorPosition do
  def decode(value, _options) do
    value
  end
end

