# NOTE: This file is auto generated by OpenAPI Generator 6.4.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DocuSign.Model.SocialAuthentication do
  @moduledoc false

  @derive [Poison.Encoder]
  defstruct [
    :authentication
  ]

  @type t :: %__MODULE__{
          :authentication => String.t() | nil
        }
end

defimpl Poison.Decoder, for: DocuSign.Model.SocialAuthentication do
  def decode(value, _options) do
    value
  end
end
