# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule DocuSign.Model.Ssn9InformationInput do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :displayLevelCode,
    :ssn9
  ]

  @type t :: %__MODULE__{
    :displayLevelCode => String.t | nil,
    :ssn9 => String.t | nil
  }
end

defimpl Poison.Decoder, for: DocuSign.Model.Ssn9InformationInput do
  def decode(value, _options) do
    value
  end
end

