# NOTE: This file is auto generated by OpenAPI Generator
# https://openapi-generator.tech
# Do not edit this file manually.

defmodule DocuSign.Model.Stamp do
  @moduledoc """

  """

  alias DocuSign.Deserializer
  alias DocuSign.Model.DateStampProperties
  alias DocuSign.Model.ErrorDetails

  @derive Jason.Encoder
  defstruct [
    :adoptedDateTime,
    :createdDateTime,
    :customField,
    :dateStampProperties,
    :disallowUserResizeStamp,
    :errorDetails,
    :externalID,
    :imageBase64,
    :imageType,
    :lastModifiedDateTime,
    :phoneticName,
    :signatureName,
    :stampFormat,
    :stampImageUri,
    :stampSizeMM,
    :status
  ]

  @type t :: %__MODULE__{
          :adoptedDateTime => String.t() | nil,
          :createdDateTime => String.t() | nil,
          :customField => String.t() | nil,
          :dateStampProperties => DateStampProperties.t() | nil,
          :disallowUserResizeStamp => String.t() | nil,
          :errorDetails => ErrorDetails.t() | nil,
          :externalID => String.t() | nil,
          :imageBase64 => String.t() | nil,
          :imageType => String.t() | nil,
          :lastModifiedDateTime => String.t() | nil,
          :phoneticName => String.t() | nil,
          :signatureName => String.t() | nil,
          :stampFormat => String.t() | nil,
          :stampImageUri => String.t() | nil,
          :stampSizeMM => String.t() | nil,
          :status => String.t() | nil
        }

  def decode(value) do
    value
    |> Deserializer.deserialize(
      :dateStampProperties,
      :struct,
      DateStampProperties
    )
    |> Deserializer.deserialize(
      :errorDetails,
      :struct,
      ErrorDetails
    )
  end
end
