# NOTE: This file is auto generated by OpenAPI Generator
# https://openapi-generator.tech
# Do not edit this file manually.

defmodule DocuSign.Model.TemplateLocks do
  @moduledoc """
  This section provides information about template locks. You use template locks to prevent others from making changes to a template while you are modifying it.
  """

  alias DocuSign.Deserializer
  alias DocuSign.Model.ErrorDetails
  alias DocuSign.Model.UserInfo

  defstruct [
    :errorDetails,
    :lockDurationInSeconds,
    :lockToken,
    :lockType,
    :lockedByApp,
    :lockedByUser,
    :lockedUntilDateTime,
    :useScratchPad
  ]

  @doc false
  defimpl Jason.Encoder, for: __MODULE__ do
    def encode(struct, opts) do
      struct
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> is_nil(v) end)
      |> Map.new()
      |> Jason.Encode.map(opts)
    end
  end

  @type t :: %__MODULE__{
          :errorDetails => ErrorDetails.t() | nil,
          :lockDurationInSeconds => String.t() | nil,
          :lockToken => String.t() | nil,
          :lockType => String.t() | nil,
          :lockedByApp => String.t() | nil,
          :lockedByUser => UserInfo.t() | nil,
          :lockedUntilDateTime => String.t() | nil,
          :useScratchPad => String.t() | nil
        }

  def decode(value) do
    value
    |> Deserializer.deserialize(
      :errorDetails,
      :struct,
      ErrorDetails
    )
    |> Deserializer.deserialize(
      :lockedByUser,
      :struct,
      UserInfo
    )
    |> then(&struct(__MODULE__, &1))
  end
end
