# NOTE: This file is auto generated by OpenAPI Generator 6.4.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DocuSign.Model.TemplateInformation do
  @moduledoc false

  @derive [Poison.Encoder]
  defstruct [
    :templates
  ]

  @type t :: %__MODULE__{
          :templates => [DocuSign.Model.TemplateSummary.t()] | nil
        }
end

defimpl Poison.Decoder, for: DocuSign.Model.TemplateInformation do
  import DocuSign.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:templates, :list, DocuSign.Model.TemplateSummary, options)
  end
end
