# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DocuSign.Model.TemplateViews do
  @moduledoc """
  Embedding template views
  """

  @derive [Poison.Encoder]
  defstruct [
    :url
  ]

  @type t :: %__MODULE__{
    :url => String.t
  }
end

defimpl Poison.Decoder, for: DocuSign.Model.TemplateViews do
  def decode(value, _options) do
    value
  end
end
