# NOTE: This file is auto generated by OpenAPI Generator 7.12.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DocuSign.Model.TemplateSharedItem do
  @moduledoc """
  Information about shared templates.
  """

  alias DocuSign.Deserializer
  alias DocuSign.Model.ErrorDetails
  alias DocuSign.Model.MemberGroupSharedItem
  alias DocuSign.Model.UserInfo
  alias DocuSign.Model.UserSharedItem

  @derive Jason.Encoder
  defstruct [
    :errorDetails,
    :owner,
    :password,
    :shared,
    :sharedGroups,
    :sharedUsers,
    :templateId,
    :templateName
  ]

  @type t :: %__MODULE__{
          :errorDetails => ErrorDetails.t() | nil,
          :owner => UserInfo.t() | nil,
          :password => String.t() | nil,
          :shared => String.t() | nil,
          :sharedGroups => [MemberGroupSharedItem.t()] | nil,
          :sharedUsers => [UserSharedItem.t()] | nil,
          :templateId => String.t() | nil,
          :templateName => String.t() | nil
        }

  def decode(value) do
    value
    |> Deserializer.deserialize(:errorDetails, :struct, ErrorDetails)
    |> Deserializer.deserialize(:owner, :struct, UserInfo)
    |> Deserializer.deserialize(:sharedGroups, :list, MemberGroupSharedItem)
    |> Deserializer.deserialize(:sharedUsers, :list, UserSharedItem)
  end
end
