# NOTE: This file is auto generated by OpenAPI Generator 7.12.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DocuSign.Model.TemplateDocumentHtmlDefinitions do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :htmlDefinitions
  ]

  @type t :: %__MODULE__{
          :htmlDefinitions => [DocuSign.Model.DocumentHtmlDefinitionOriginal.t()] | nil
        }

  alias DocuSign.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(
      :htmlDefinitions,
      :list,
      DocuSign.Model.DocumentHtmlDefinitionOriginal
    )
  end
end
