# NOTE: This file is auto generated by OpenAPI Generator
# https://openapi-generator.tech
# Do not edit this file manually.

defmodule DocuSign.Model.TemplateCompletionRateResponse do
  @moduledoc """

  """

  alias DocuSign.Deserializer
  alias DocuSign.Model.SenderCompletionInfo

  defstruct [
    :bottomSenders,
    :completed,
    :completionRate,
    :expired,
    :expiredRate,
    :sent,
    :topSenders,
    :voided,
    :voidedRate
  ]

  @doc false
  defimpl Jason.Encoder, for: __MODULE__ do
    def encode(struct, opts) do
      struct
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> is_nil(v) end)
      |> Map.new()
      |> Jason.Encode.map(opts)
    end
  end

  @type t :: %__MODULE__{
          :bottomSenders => [SenderCompletionInfo.t()] | nil,
          :completed => integer() | nil,
          :completionRate => float() | nil,
          :expired => integer() | nil,
          :expiredRate => float() | nil,
          :sent => integer() | nil,
          :topSenders => [SenderCompletionInfo.t()] | nil,
          :voided => integer() | nil,
          :voidedRate => float() | nil
        }

  def decode(value) do
    value
    |> Deserializer.deserialize(
      :bottomSenders,
      :list,
      SenderCompletionInfo
    )
    |> Deserializer.deserialize(
      :topSenders,
      :list,
      SenderCompletionInfo
    )
    |> then(&struct(__MODULE__, &1))
  end
end
