# NOTE: This file is auto generated by OpenAPI Generator 6.4.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DocuSign.Model.TemplateBulkRecipients do
  @moduledoc """
  Template bulk recipients
  """

  @derive [Poison.Encoder]
  defstruct [
    :bulkRecipients,
    :endPosition,
    :nextUri,
    :previousUri,
    :resultSetSize,
    :startPosition,
    :totalSetSize
  ]

  @type t :: %__MODULE__{
          :bulkRecipients => [DocuSign.Model.BulkRecipient.t()] | nil,
          :endPosition => String.t() | nil,
          :nextUri => String.t() | nil,
          :previousUri => String.t() | nil,
          :resultSetSize => String.t() | nil,
          :startPosition => String.t() | nil,
          :totalSetSize => String.t() | nil
        }
end

defimpl Poison.Decoder, for: DocuSign.Model.TemplateBulkRecipients do
  import DocuSign.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:bulkRecipients, :list, DocuSign.Model.BulkRecipient, options)
  end
end
