# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DocuSign.Model.TextCustomField do
  @moduledoc """
  This object represents a free text custom field where envelope creators and senders can enter custom data.
  """

  @derive [Poison.Encoder]
  defstruct [
    :configurationType,
    :errorDetails,
    :fieldId,
    :name,
    :required,
    :show,
    :value
  ]

  @type t :: %__MODULE__{
          :configurationType => String.t() | nil,
          :errorDetails => DocuSign.Model.ErrorDetails.t() | nil,
          :fieldId => String.t() | nil,
          :name => String.t() | nil,
          :required => String.t() | nil,
          :show => String.t() | nil,
          :value => String.t() | nil
        }
end

defimpl Poison.Decoder, for: DocuSign.Model.TextCustomField do
  import DocuSign.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:errorDetails, :struct, DocuSign.Model.ErrorDetails, options)
  end
end
