# NOTE: This file is auto generated by OpenAPI Generator 7.12.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DocuSign.Model.UserAuthorizationsDeleteResponse do
  @moduledoc """

  """

  alias DocuSign.Deserializer
  alias DocuSign.Model.UserAuthorizationIdWithStatus

  @derive Jason.Encoder
  defstruct [
    :results
  ]

  @type t :: %__MODULE__{
          :results => [UserAuthorizationIdWithStatus.t()] | nil
        }

  def decode(value) do
    value
    |> Deserializer.deserialize(:results, :list, UserAuthorizationIdWithStatus)
  end
end
