# NOTE: This file is auto generated by OpenAPI Generator 7.12.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DocuSign.Model.UserInfoList do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :users
  ]

  @type t :: %__MODULE__{
          :users => [DocuSign.Model.UserInfo.t()] | nil
        }

  alias DocuSign.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:users, :list, DocuSign.Model.UserInfo)
  end
end
