# NOTE: This file is auto generated by OpenAPI Generator 7.12.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DocuSign.Model.UserAuthorization do
  @moduledoc """
  A complex object describing a user authorization.
  """

  @derive Jason.Encoder
  defstruct [
    :agentUser,
    :authorizationId,
    :created,
    :createdBy,
    :endDate,
    :modified,
    :modifiedBy,
    :permission,
    :principalUser,
    :startDate
  ]

  @type t :: %__MODULE__{
          :agentUser => DocuSign.Model.AuthorizationUser.t() | nil,
          :authorizationId => String.t() | nil,
          :created => String.t() | nil,
          :createdBy => String.t() | nil,
          :endDate => String.t() | nil,
          :modified => String.t() | nil,
          :modifiedBy => String.t() | nil,
          :permission => String.t() | nil,
          :principalUser => DocuSign.Model.AuthorizationUser.t() | nil,
          :startDate => String.t() | nil
        }

  alias DocuSign.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:agentUser, :struct, DocuSign.Model.AuthorizationUser)
    |> Deserializer.deserialize(:principalUser, :struct, DocuSign.Model.AuthorizationUser)
  end
end
