# NOTE: This file is auto generated by OpenAPI Generator 7.12.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DocuSign.Model.UserSignaturesInformation do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :userSignatures
  ]

  @type t :: %__MODULE__{
          :userSignatures => [DocuSign.Model.UserSignature.t()] | nil
        }

  alias DocuSign.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:userSignatures, :list, DocuSign.Model.UserSignature)
  end
end
