# NOTE: This file is auto generated by OpenAPI Generator
# https://openapi-generator.tech
# Do not edit this file manually.

defmodule DocuSign.Model.WorkspaceUserAuthorization do
  @moduledoc """
  Provides properties that describe user authorization to a workspace.
  """

  alias DocuSign.Deserializer
  alias DocuSign.Model.ErrorDetails
  alias DocuSign.Model.WorkspaceUser

  defstruct [
    :canDelete,
    :canMove,
    :canTransact,
    :canView,
    :created,
    :createdById,
    :errorDetails,
    :modified,
    :modifiedById,
    :workspaceUserId,
    :workspaceUserInformation
  ]

  @doc false
  defimpl Jason.Encoder, for: __MODULE__ do
    def encode(struct, opts) do
      struct
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> is_nil(v) end)
      |> Map.new()
      |> Jason.Encode.map(opts)
    end
  end

  @type t :: %__MODULE__{
          :canDelete => String.t() | nil,
          :canMove => String.t() | nil,
          :canTransact => String.t() | nil,
          :canView => String.t() | nil,
          :created => String.t() | nil,
          :createdById => String.t() | nil,
          :errorDetails => ErrorDetails.t() | nil,
          :modified => String.t() | nil,
          :modifiedById => String.t() | nil,
          :workspaceUserId => String.t() | nil,
          :workspaceUserInformation => WorkspaceUser.t() | nil
        }

  def decode(value) do
    value
    |> Deserializer.deserialize(
      :errorDetails,
      :struct,
      ErrorDetails
    )
    |> Deserializer.deserialize(
      :workspaceUserInformation,
      :struct,
      WorkspaceUser
    )
    |> then(&struct(__MODULE__, &1))
  end
end
