# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule DocuSign.Model.WorkspaceSettings do
  @moduledoc """
  This object provides information about the settings for the workspace.
  """

  @derive [Poison.Encoder]
  defstruct [
    :commentsAllowed
  ]

  @type t :: %__MODULE__{
    :commentsAllowed => String.t | nil
  }
end

defimpl Poison.Decoder, for: DocuSign.Model.WorkspaceSettings do
  def decode(value, _options) do
    value
  end
end

