# NOTE: This file is auto generated by OpenAPI Generator 7.12.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DocuSign.Model.WorkflowStep do
  @moduledoc """
  Describes a single step in a workflow.
  """

  @derive Jason.Encoder
  defstruct [
    :action,
    :completedDate,
    :delayedRouting,
    :itemId,
    :recipientRouting,
    :status,
    :triggeredDate,
    :triggerOnItem,
    :workflowStepId
  ]

  @type t :: %__MODULE__{
          :action => String.t() | nil,
          :completedDate => String.t() | nil,
          :delayedRouting => DocuSign.Model.DelayedRouting.t() | nil,
          :itemId => String.t() | nil,
          :recipientRouting => DocuSign.Model.RecipientRouting.t() | nil,
          :status => String.t() | nil,
          :triggeredDate => String.t() | nil,
          :triggerOnItem => String.t() | nil,
          :workflowStepId => String.t() | nil
        }

  alias DocuSign.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:delayedRouting, :struct, DocuSign.Model.DelayedRouting)
    |> Deserializer.deserialize(:recipientRouting, :struct, DocuSign.Model.RecipientRouting)
  end
end
