# NOTE: This file is auto generated by OpenAPI Generator 7.12.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DocuSign.Model.WorkspaceFolderContents do
  @moduledoc """
  This object's properties describe the contents of a workspace folder.
  """

  alias DocuSign.Deserializer
  alias DocuSign.Model.WorkspaceItem

  @derive Jason.Encoder
  defstruct [
    :endPosition,
    :folder,
    :items,
    :parentFolders,
    :resultSetSize,
    :startPosition,
    :totalSetSize,
    :workspaceId
  ]

  @type t :: %__MODULE__{
          :endPosition => String.t() | nil,
          :folder => WorkspaceItem.t() | nil,
          :items => [WorkspaceItem.t()] | nil,
          :parentFolders => [WorkspaceItem.t()] | nil,
          :resultSetSize => String.t() | nil,
          :startPosition => String.t() | nil,
          :totalSetSize => String.t() | nil,
          :workspaceId => String.t() | nil
        }

  def decode(value) do
    value
    |> Deserializer.deserialize(:folder, :struct, WorkspaceItem)
    |> Deserializer.deserialize(:items, :list, WorkspaceItem)
    |> Deserializer.deserialize(:parentFolders, :list, WorkspaceItem)
  end
end
