# NOTE: This file is auto generated by OpenAPI Generator 7.12.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DocuSign.Api.AccountTabSettings do
  @moduledoc """
  API calls for all endpoints tagged `AccountTabSettings`.
  """

  import DocuSign.RequestBuilder

  alias DocuSign.Connection
  alias DocuSign.Model.ErrorDetails
  alias DocuSign.Model.TabAccountSettings

  @doc """
  Returns tab settings list for specified account
  This method returns information about the tab types and tab functionality that is currently enabled for an account.

  ### Parameters

  - `connection` (DocuSign.Connection): Connection to server
  - `account_id` (String.t): The external account number (int) or account ID GUID.
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, DocuSign.Model.TabAccountSettings.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec tab_settings_get_tab_settings(Tesla.Env.client(), String.t(), keyword()) ::
          {:ok, TabAccountSettings.t()}
          | {:ok, ErrorDetails.t()}
          | {:error, Tesla.Env.t()}
  def tab_settings_get_tab_settings(connection, account_id, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/v2.1/accounts/#{account_id}/settings/tabs")
      |> Enum.to_list()

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, TabAccountSettings},
      {400, ErrorDetails}
    ])
  end

  @doc """
  Modifies tab settings for specified account
  This method modifies the tab types and tab functionality that is enabled for an account.

  ### Parameters

  - `connection` (DocuSign.Connection): Connection to server
  - `account_id` (String.t): The external account number (int) or account ID GUID.
  - `opts` (keyword): Optional parameters
    - `:body` (TabAccountSettings): Account-wide tab settings.

  ### Returns

  - `{:ok, DocuSign.Model.TabAccountSettings.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec tab_settings_put_settings(Tesla.Env.client(), String.t(), keyword()) ::
          {:ok, TabAccountSettings.t()}
          | {:ok, ErrorDetails.t()}
          | {:error, Tesla.Env.t()}
  def tab_settings_put_settings(connection, account_id, opts \\ []) do
    optional_params = %{
      :body => :body
    }

    request =
      %{}
      |> method(:put)
      |> url("/v2.1/accounts/#{account_id}/settings/tabs")
      |> add_optional_params(optional_params, opts)
      |> ensure_body()
      |> Enum.to_list()

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, TabAccountSettings},
      {400, ErrorDetails}
    ])
  end
end
