# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DocuSign.Api.EMortgageTransactions do
  @moduledoc """
  API calls for all endpoints tagged `EMortgageTransactions`.
  """

  alias DocuSign.Connection
  import DocuSign.RequestBuilder

  @doc """
  Starts a new eMortgage Transaction
  Deprecated: This method will be removed in a future release

  ## Parameters

  - connection (DocuSign.Connection): Connection to server
  - account_id (String.t): The external account number (int) or account ID Guid.
  - opts (KeywordList): [optional] Optional parameters
    - :e_mortgage_transactions (EMortgageTransactions): 

  ## Returns

  {:ok, %DocuSign.Model.PostTransactionsResponse{}} on success
  {:error, info} on failure
  """
  @spec e_mortgage_post_transactions(Tesla.Env.client(), String.t(), keyword()) ::
          {:ok, DocuSign.Model.PostTransactionsResponse.t()} | {:error, Tesla.Env.t()}
  def e_mortgage_post_transactions(connection, account_id, opts \\ []) do
    optional_params = %{
      :EMortgageTransactions => :body
    }

    %{}
    |> method(:post)
    |> url("/v2/accounts/#{account_id}/eMortgage/transactions")
    |> add_optional_params(optional_params, opts)
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> decode(%DocuSign.Model.PostTransactionsResponse{})
  end
end
