# NOTE: This file is auto generated by OpenAPI Generator 7.12.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DocuSign.Api.EnvelopeHtmlDefinitions do
  @moduledoc """
  API calls for all endpoints tagged `EnvelopeHtmlDefinitions`.
  """

  alias DocuSign.Connection
  import DocuSign.RequestBuilder

  @doc """
  Gets the Original HTML Definition used to generate the Responsive HTML for the envelope.

  ### Parameters

  - `connection` (DocuSign.Connection): Connection to server
  - `account_id` (String.t): The external account number (int) or account ID GUID.
  - `envelope_id` (String.t): The envelope's GUID.   Example: `93be49ab-xxxx-xxxx-xxxx-f752070d71ec` 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, DocuSign.Model.DocumentHtmlDefinitionOriginals.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec responsive_html_get_envelope_html_definitions(
          Tesla.Env.client(),
          String.t(),
          String.t(),
          keyword()
        ) ::
          {:ok, DocuSign.Model.ErrorDetails.t()}
          | {:ok, DocuSign.Model.DocumentHtmlDefinitionOriginals.t()}
          | {:error, Tesla.Env.t()}
  def responsive_html_get_envelope_html_definitions(
        connection,
        account_id,
        envelope_id,
        _opts \\ []
      ) do
    request =
      %{}
      |> method(:get)
      |> url("/v2.1/accounts/#{account_id}/envelopes/#{envelope_id}/html_definitions")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, DocuSign.Model.DocumentHtmlDefinitionOriginals},
      {400, DocuSign.Model.ErrorDetails}
    ])
  end
end
