# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule DocuSign.Api.Services do
  @moduledoc """
  API calls for all endpoints tagged `Services`.
  """

  alias DocuSign.Connection
  import DocuSign.RequestBuilder


  @doc """
  Retrieves the available REST API versions.
  Retrieves the available REST API versions.  DocuSign Production system: https://www.docusign.net/restapi/service_information DocuSign Demo system: https://demo.docusign.net/restapi/service_information  You do not need an integration key to view the REST API versions and resources.

  ## Parameters

  - connection (DocuSign.Connection): Connection to server
  - opts (KeywordList): [optional] Optional parameters
  ## Returns

  {:ok, DocuSign.Model.ServiceInformation.t} on success
  {:error, Tesla.Env.t} on failure
  """
  @spec service_information_get_service_information(Tesla.Env.client, keyword()) :: {:ok, DocuSign.Model.ErrorDetails.t} | {:ok, DocuSign.Model.ServiceInformation.t} | {:error, Tesla.Env.t}
  def service_information_get_service_information(connection, _opts \\ []) do
    %{}
    |> method(:get)
    |> url("/service_information")
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> evaluate_response([
      { 200, %DocuSign.Model.ServiceInformation{}},
      { 400, %DocuSign.Model.ErrorDetails{}}
    ])
  end
end
